service: road-so-far-api

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2

functions:
  auth:
    handler: handler.auth
  graphql:
    handler: handler.graphql
    events:
    - http:
        path: graphql
        method: post
        cors: true
        integration: lambda
        authorizer: auth
