service: road-so-far-api

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  api:
    handler: handler.graphql
    events:
    - http:
        path: graphql
        method: post
        cors: true
        integration: lambda
        response:
          headers:
            Access-Control-Allow-Origin: "'*'"
